### ISSUE TITLE
[문구 수정 요청] 정확한 정보 기재 부탁드립니다.

### ISSUE THREAD

**Issue by zero734kr** [Yoruroong/zip_password_recovery#1]
[이 문단](https://github.com/Yoruroong/zip_password_recovery#예상되는-시간-소문자-대문자-특수문자-숫자)에서는 그저 최신 i5 CPU라고 안내하고 있습니다만 이 최신형이 인텔 코어 i 시리즈의 10세대를 지칭하는지 또는 9세대를 지칭하는지 불명확합니다. 또한 i5도 모델에 따라 차이가 있을수 있기에 정확한 모델명 기재 부탁드립니다.

**Comment by Yoruroong** [comment]
[#15](https://github.com/Yoruroong/zip_password_recovery/commit/69d3462aabde065cb411d5c12c72f090a5720b4a)
